name: Generate Changelog

on:
  workflow_dispatch:
    inputs:
      from_tag:
        description: 'Start tag (leave empty for previous tag)'
        required: false
        type: string
      to_tag:
        description: 'End tag (leave empty for HEAD)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: read

jobs:
  generate-changelog:
    name: Generate and Update Changelog
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        configuration: ".github/changelog-config.json"
        outputFile: CHANGELOG.md
        fromTag: ${{ inputs.from_tag }}
        toTag: ${{ inputs.to_tag }}
        commitMode: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Display changelog
      run: |
        echo "Generated Changelog:"
        cat CHANGELOG.md
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'docs: update CHANGELOG.md'
        title: 'Update CHANGELOG.md'
        body: |
          This PR updates the CHANGELOG.md file with the latest changes.
          
          Generated from commits between tags:
          - From: ${{ inputs.from_tag || 'previous tag' }}
          - To: ${{ inputs.to_tag || 'HEAD' }}
        branch: update-changelog
        delete-branch: true
        labels: documentation
